Repository sendsmaily/smaily-opencart-module, pull requests merged in 2020-11, with the labels that each got.

#101 Update release pull request template
  .github/pull_request_template.md
Labels: enhancement, maintenance

#102 Add lang field to form
  upload/catalog/controller/extension/module/smaily_for_opencart.php
  upload/catalog/view/theme/default/template/extension/module/smaily_for_opencart.twig
Labels: 3.0.x, enhancement

#103 Add lang field to form
  upload/catalog/controller/extension/module/smaily_for_opencart.php
  upload/catalog/view/theme/default/template/extension/module/smaily_for_opencart.tpl
Labels: 2.3.x, enhancement

#104 Add lang field to form
  upload/catalog/controller/module/smaily_for_opencart.php
  upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
Labels: 2.2.x, enhancement

#105 Add lang field to form
  upload/catalog/controller/module/smaily_for_opencart.php
  upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
Labels: 1.5.x, enhancement

#106 Add first iteration of contribution guide
  .github/workflows/release.yaml
  CONTRIBUTING.md
Labels: documentation, maintenance

#107 Simplify development environment management
  .sandbox/entrypoint.sh
  docker-compose.yaml
Labels: enhancement, maintenance

#109 Simplify development environment management
  .sandbox/entrypoint.sh
  docker-compose.yaml
Labels: 2.2.x, enhancement, maintenance

#108 Add first iteration of the contribution guide
  .github/workflows/release.yaml
  CONTRIBUTING.md
Labels: 2.2.x, documentation, maintenance

#111 Add first iteration of the contribution guide
  .github/workflows/release.yaml
  CONTRIBUTING.md
Labels: 2.3.x, documentation, maintenance

#112 Simplify development environment management
  .sandbox/entrypoint.sh
  docker-compose.yaml
Labels: 2.3.x, enhancement, maintenance

#115 Unify development environment installation base URL with other versions
  .sandbox/entrypoint.sh
Labels: 1.5.x, maintenance

#113 Release 1.2.0 for 1.5.x
  CHANGELOG.md
  README.md
  assets/screenshot-5.png
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/language/english/module/smaily_for_opencart.php
  upload/admin/view/template/module/smaily_for_opencart.tpl
  upload/catalog/controller/module/smaily_for_opencart.php
  upload/catalog/controller/smailyforopencart/rss.php
  upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
Labels: 1.5.x, release

#114 Release 1.4.0 for 2.2x
  CHANGELOG.md
  README.md
  assets/screenshot-6.png
  install.xml
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/language/en-gb/module/smaily_for_opencart.php
  upload/admin/view/template/module/smaily_for_opencart.tpl
  upload/catalog/controller/module/smaily_for_opencart.php
  upload/catalog/controller/smailyforopencart/cron_customers.php
  upload/catalog/controller/smailyforopencart/rss.php
  upload/catalog/view/theme/default/template/module/smaily_for_opencart.tpl
Labels: 2.2.x, release

#116 Release 1.4.0 for 2.3.x
  CHANGELOG.md
  README.md
  assets/screenshot-6.png
  install.xml
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/view/template/extension/module/smaily_for_opencart.tpl
  upload/catalog/controller/extension/module/smaily_for_opencart.php
  upload/catalog/controller/extension/smailyforopencart/cron_customers.php
  upload/catalog/controller/extension/smailyforopencart/rss.php
  upload/catalog/view/theme/default/template/extension/module/smaily_for_opencart.tpl
Labels: 2.3.x, release

#117 Release 1.4.0 for 3.0.x
  CHANGELOG.md
  README.md
  assets/screenshot-6.png
  install.xml
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/view/javascript/smailyforopencart/smaily_admin.js
  upload/admin/view/template/extension/module/smaily_for_opencart.twig
  upload/catalog/controller/extension/module/smaily_for_opencart.php
  upload/catalog/controller/extension/smailyforopencart/cron_customers.php
  upload/catalog/controller/extension/smailyforopencart/rss.php
  upload/catalog/view/theme/default/template/extension/module/smaily_for_opencart.twig
Labels: 3.0.x, release

#122 Simplify development environment management
  .sandbox/entrypoint.sh
  docker-compose.yaml
Labels: 3.0.x, enhancement, maintenance

#121 Add first iteration of contribution guide
  .github/workflows/release.yaml
  CONTRIBUTING.md
Labels: 3.0.x, documentation, maintenance

#119 Improve phrasing of environment resetting section
  CONTRIBUTING.md
Labels: 2.2.x, documentation, maintenance

#118 Improve phrasing of environment resetting section
  CONTRIBUTING.md
Labels: 1.5.x, documentation, maintenance

#120 Improve phrasing of environment resetting section
  CONTRIBUTING.md
Labels: 2.3.x, documentation, maintenance

#123 Add abandoned cart page
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/model/extension/smailyforopencart/admin.php
  upload/admin/view/javascript/smailyforopencart/smaily_admin.js
  upload/admin/view/template/extension/module/smaily_for_opencart.twig
  upload/admin/view/theme/default/stylesheet/smaily_oc.css
  upload/modman
Labels: 3.0.x, enhancement

#127 Add abandoned cart status page
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/language/en-gb/module/smaily_for_opencart.php
  upload/admin/model/smailyforopencart/admin.php
  upload/admin/view/stylesheet/smaily_oc.css
  upload/admin/view/template/module/smaily_for_opencart.tpl
  upload/modman
Labels: 2.2.x, enhancement

#126 Add abandoned cart status page
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/model/extension/smailyforopencart/admin.php
  upload/admin/view/stylesheet/smaily_oc.css
  upload/admin/view/template/extension/module/smaily_for_opencart.tpl
  upload/modman
Labels: 2.3.x, enhancement
