Repository sendsmaily/smaily-opencart-module, pull requests merged in 2020-12, with the labels that each got.

#130 Display module version
  upload/admin/controller/extension/module/smaily_for_opencart.php
Labels: 3.0.x, enhancement

#129 Bump OC versions
  Dockerfile
  README.md
Labels: 3.0.x, maintenance

#134 Display module version
  upload/admin/controller/extension/module/smaily_for_opencart.php
Labels: 2.3.x, enhancement

#135 Display module version
  upload/admin/controller/module/smaily_for_opencart.php
Labels: 2.2.x, enhancement

#136 Display module version
  upload/admin/controller/module/smaily_for_opencart.php
Labels: 1.5.x, enhancement

#133 Add reminder to update version in controller checklist
  .github/pull_request_template.md
Labels: maintenance

#137 Move cURL calls to a seperate Request library
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/model/extension/smailyforopencart/admin.php
  upload/catalog/controller/extension/smailyforopencart/cron_cart.php
  upload/catalog/controller/extension/smailyforopencart/cron_customers.php
  upload/catalog/model/extension/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smailyforopencart/request.php
Labels: 3.0.x, enhancement

#140 Move cURL calls to a seperate Request library
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/model/extension/smailyforopencart/admin.php
  upload/catalog/controller/extension/smailyforopencart/cron_cart.php
  upload/catalog/controller/extension/smailyforopencart/cron_customers.php
  upload/catalog/model/extension/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smailyforopencart/request.php
Labels: 2.3.x, enhancement

#141 Move cURL calls to a seperate Request library
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/language/en-gb/module/smaily_for_opencart.php
  upload/admin/model/smailyforopencart/admin.php
  upload/catalog/controller/smailyforopencart/cron_cart.php
  upload/catalog/controller/smailyforopencart/cron_customers.php
  upload/catalog/model/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smailyforopencart/request.php
Labels: 2.2.x, enhancement

#142 Move cURL calls to a seperate Request library
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/model/smailyforopencart/admin.php
  upload/catalog/controller/smailyforopencart/cron_customers.php
  upload/catalog/model/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smaily_for_opencart_request.php
Labels: 1.5.x, enhancement

#144 Fix unsubscribing in chunks not working in chunks
  upload/catalog/model/smailyforopencart/helper.php
Labels: 1.5.x, bug

#145 Unsubscribing in chunks doesn't work in chunks
  upload/catalog/model/smailyforopencart/helper.php
Labels: 2.2.x, bug

#146 Unsubscribing in chunks doesn't work in chunks
  upload/catalog/model/extension/smailyforopencart/helper.php
Labels: 2.3.x, bug

#148 Remove unused function to retrieve API credentials
  upload/catalog/model/smailyforopencart/helper.php
Labels: 1.5.x, maintenance

#149 Add missing identation
  upload/admin/model/extension/smailyforopencart/admin.php
Labels: 3.0.x, maintenance

#150 Fix/rss limit value error 2.3.x
  upload/admin/controller/extension/module/smaily_for_opencart.php
Labels: 2.3.x, bug

#151 Fix/rss limit value error 2.2.x
  upload/admin/controller/module/smaily_for_opencart.php
Labels: 2.2.x, bug

#152 Fix/rss limit value error 3.0.x
  upload/admin/controller/extension/module/smaily_for_opencart.php
Labels: 3.0.x, bug

#154 1.3.0 for 1.5.x release checklist changes
  CHANGELOG.md
  upload/admin/controller/module/smaily_for_opencart.php
Labels: 1.5.x, maintenance

#159 1.5.0 for 2.3.x release checklist changes
  CHANGELOG.md
  install.xml
  upload/admin/controller/extension/module/smaily_for_opencart.php
Labels: 2.3.x, maintenance

#160 1.5.0 for 3.0.x release checklist changes
  CHANGELOG.md
  install.xml
  upload/admin/controller/extension/module/smaily_for_opencart.php
Labels: 3.0.x, maintenance

#156 1.5.0 for 2.2.x release checklist changes
  CHANGELOG.md
  install.xml
  upload/admin/controller/module/smaily_for_opencart.php
Labels: 2.2.x, maintenance

#147 Unsubscribing in chunks doesn't work in chunks
  upload/catalog/model/extension/smailyforopencart/helper.php
Labels: 3.0.x, bug

#161 Include abandoned cart page documentation in 1.5.0 for for 2.2.x
  CHANGELOG.md
  README.md
Labels: 2.2.x, maintenance

#163 Include abandoned cart page documentation in 1.5.0 for for 3.0.x
  CHANGELOG.md
  README.md
Labels: 3.0.x, maintenance

#162 Include abandoned cart page documentation in 1.5.0 for for 2.3.x
  CHANGELOG.md
  README.md
Labels: 2.3.x, maintenance

#153 Release 1.3.0 for 1.5.x
  CHANGELOG.md
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/model/smailyforopencart/admin.php
  upload/catalog/controller/smailyforopencart/cron_customers.php
  upload/catalog/model/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smaily_for_opencart_request.php
Labels: 1.5.x, release

#155 Release 1.5.0 for 2.2.x
  CHANGELOG.md
  README.md
  install.xml
  upload/admin/controller/module/smaily_for_opencart.php
  upload/admin/language/en-gb/module/smaily_for_opencart.php
  upload/admin/model/smailyforopencart/admin.php
  upload/admin/view/stylesheet/smaily_oc.css
  upload/admin/view/template/module/smaily_for_opencart.tpl
  upload/catalog/controller/smailyforopencart/cron_cart.php
  upload/catalog/controller/smailyforopencart/cron_customers.php
  upload/catalog/model/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smailyforopencart/request.php
Labels: 2.2.x, release

#157 Release 1.5.0 for 2.3.x
  CHANGELOG.md
  README.md
  install.xml
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/model/extension/smailyforopencart/admin.php
  upload/admin/view/stylesheet/smaily_oc.css
  upload/admin/view/template/extension/module/smaily_for_opencart.tpl
  upload/catalog/controller/extension/smailyforopencart/cron_cart.php
  upload/catalog/controller/extension/smailyforopencart/cron_customers.php
  upload/catalog/model/extension/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smailyforopencart/request.php
Labels: 2.3.x, release

#158 Release 1.5.0 for 3.0.x
  CHANGELOG.md
  Dockerfile
  README.md
  install.xml
  upload/admin/controller/extension/module/smaily_for_opencart.php
  upload/admin/language/en-gb/extension/module/smaily_for_opencart.php
  upload/admin/model/extension/smailyforopencart/admin.php
  upload/admin/view/javascript/smailyforopencart/smaily_admin.js
  upload/admin/view/template/extension/module/smaily_for_opencart.twig
  upload/admin/view/theme/default/stylesheet/smaily_oc.css
  upload/catalog/controller/extension/smailyforopencart/cron_cart.php
  upload/catalog/controller/extension/smailyforopencart/cron_customers.php
  upload/catalog/model/extension/smailyforopencart/helper.php
  upload/modman
  upload/system/library/smailyforopencart/request.php
Labels: 3.0.x, release

#165 Update marketing screenshots
  assets/screenshot-1.png
  assets/screenshot-2.png
  assets/screenshot-3.png
  assets/screenshot-6.png
  assets/screenshot-7.png
Labels: documentation, maintenance
